namespace VideoGameCharacterApi.Dtos
{
    public class CharacterResponse
    {
        // Unique identifier generated by the database.
        public int Id { get; set; }

        // Name returned to API clients.
        public string Name { get; set; } = string.Empty;

        // Game returned to API clients.
        public string Game { get; set; } = string.Empty;

        // Role returned to API clients.
        public string Role { get; set; } = string.Empty;

        // This DTO is used to shape responses so we don't expose EF entities directly.
    }
}
